---
# Multiarch build file credits go to Lars Kellogg-Stedman at blog.oddbit.com. If You ever see this - thanks!
name: "build images"

on:
  push:
    branches:
      - master
    tags:        
      - 'v*'
  workflow_dispatch:

jobs:
  docker:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@f7b4ed12385588c3f9bc252f0a2b520d83b52d48
        with:
          images: "ghcr.io/${{ github.repository }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@cfed4e995e12d7bee5002f066f5649e5f1cc059c
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GITHUB_REF=${{ github.ref_name || github.ref || 'unknown' }}
        env:
          # should make it reproducable - https://docs.docker.com/build/ci/github-actions/reproducible-builds/
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

      # - name: Build DM
      #   uses: docker/build-push-action@cfed4e995e12d7bee5002f066f5649e5f1cc059c
      #   with:
      #     context: .
      #     file: ./Dockerfile.dm
      #     push: true
      #     platforms: linux/amd64,linux/arm64
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
